name: Pre-Merge
description: |
  This workflow runs on pull requests to the main branch and checks Terraform configurations.
  It ensures that the Terraform code is formatted, initialized, and validated.
  It does not run a plan or apply, as those are typically reserved for manual or scheduled workflows.

on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  TF_VERSION: 1.11.3
  TF_VAR_ENVIRONMENT: prd
  # TF_VAR_snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  # TF_VAR_snowflake_user: ${{ secrets.SNOWFLAKE_USER }}
  # TF_VAR_snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
  # TF_VAR_snowflake_role: ${{ secrets.SNOWFLAKE_ROLE }}
  # TF_VAR_snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
  # TF_VAR_snowflake_database: ${{ secrets.SNOWFLAKE_DATABASE }}
  # TF_VAR_snowflake_schema: ${{ secrets.SNOWFLAKE_SCHEMA }}

defaults:
  run:
    shell: bash
    working-directory: ./terraform/

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3
          # terraform_wrapper: false
      - name: Terraform fmt
        run: |
          terraform fmt --check
      - name: Configure AWS Credentials for China region audience
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      - name: Terraform init
        run: |
          terraform init \
            --backend-config="key=snowflake/${{ env.TF_VAR_ENVIRONMENT }}/terraform.tfstate"
      - name: Terraform validate
        run: |
          terraform validate -no-color


# tflint / checkov などの静的解析ツール

# terraform plan (ターゲットはprd環境。出力結果をPRコメントとして投稿)
# ポイント: このステップでdev環境のplanは通常不要です。なぜなら、最終的にmainブランチにマージされるのはprd環境に適用される変更だからです。